### ISSUE TITLE
How to set Vertical align for content into mCSB_container?

### ISSUE THREAD

**Issue by igribkov** [malihu/malihu-custom-scrollbar-plugin#222]
For example I have this html code

``` html
    <div class="main-description mCustomScrollbar">
         <div class="js-content-area"></div>                  
    </div>
```

And I have js

``` javascript
    function addToMainContent(content) {
         if (content) {
             $(".js-content-area").html(content);
         }
    }
```

And CSS for main-description

``` CSS
    .main-description {
        position: absolute;
        width: 100%;
        top: 155px;
        bottom: 10px;
        background: url("../images/test_comn_bg.png");
   }
```

So in JS `content` variable can contain everything what i want, texts, html-tags (`<div>LONG TEXT HERE</div>` or `<div>SHORT TEXT1</div><div>SHORT TEXT 2</div>`)
I would like to know, if vertical size of content less than vertical size of container is it possible to set `vertical-align: middle` for content? How i should do this?
Tnx :)
