### ISSUE TITLE
Element gone when adding scrollbar

### ISSUE THREAD

**Issue by Goeny** [malihu/malihu-custom-scrollbar-plugin#301]
I am working on a template where i want to use the scrollbar.

The template is based on bootstrap framework, using a fixed sidebar.
On that sidebar i want to use the scrollbar. But as soon as i add it, the contents of the sidebar are gone.
I can see the contents for a split second but as soon as the scrollbar loads, the contents are gone.

 ```html
<!-- how the sidepanel is build (in the real one, items have accordion items) -->
<div id="sidebar-wrapper" class="sidepanel-collapse-menu">
        	<ul class="sidebar-nav">
        		<li>item</li>
        		<li>item</li>
        		<li>item</li>
</ul>
    	</div>
```
```css
#sidebar-wrapper {
  margin-left: -250px;
  left: 250px;
  width: 250px;
  height: 100%;
  background-color: #333;
  box-shadow: 5px 0px 6px #000;
  -o-box-shadow: 5px 0px 6px #000;
  -moz-box-shadow: 5px 0px 6px #000;
  -webkit-box-shadow: 5px 0px 6px #000;
  position: fixed;
  overflow: hidden;
  z-index: 1000;
  transition: all 0.4s ease 0s;
  -o-transition: all 0.4s ease 0s;
  -moz-transition: all 0.4s ease 0s;
  -webkit-transition: all 0.4s ease 0s;
}
```

I use the same scrollbar, within the same page where it works flawless. but even when i remove that, it doesn't work on the sidebar.
