### ISSUE TITLE
[Question] Is it possible use Custom-Scrollbar for 2-side pages?

### ISSUE THREAD

**Issue by Kristinita** [malihu/malihu-custom-scrollbar-plugin#501]
### 1. Briefly

I can not understand, how I can use Custom-Scrollbar for my 2-side pages. Is it possible? If yes, what I should do?

### 2. Detail

My test page with Custom-Scrollbar plugin — **<https://github.com/Kristinita/Kristinita.github.io/blob/master/Sublime-Text/Test3.html>**.

Structure of my page:

```html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
    <aside></aside>
    <main></main>
</body>
</html>
```

![My page](http://i.imgur.com/KO7ssKm.png)

I want to set my custom scroll bar in left side of my page.

And I use [**media queries**](https://github.com/Kristinita/Kristinita.github.io/blob/master/css/general/style.css#L172-L219):

```css
@media screen and (min-width: 1px)
{
    .sidebar
    {
        display: block;
    }
}
@media screen and (min-width: 960px)
{
    .sidebar
    {
        position: fixed;
        z-index: 200;
        top: 0;

        display: block;

        width: 35%;
        height: 100%;

        background-attachment: scroll;
    }
}
```

I don't want have scrollbar on mobile devices.

![Mobile devices](http://i.imgur.com/O82LZex.png)

### 3. Did not help

1. I don't find in [**documentation page**](http://manos.malihu.gr/jquery-custom-content-scroller/#expand-info), how I can move scrollbar to left side.
2. I don't find in documentation page, how I can disable scrollbar near top image on mobile devices.

Thanks.
